apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-kube-app
  template:
    metadata:
      labels:
        app: node-kube-app
    spec:
      containers:
        - name: node-kube-app
          image: node-kube-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
